---
title: "Assignment 02"
subtitle: "C++ Object-oriented Programming"
author:
    Khiem Nguyen 
    <br> Lecturer in Multiscale Materials
    <br> <khiem.nguyen@glasgow.ac.uk>
author-meta: "Lecturer in Multiscale Materials"
jupyter: false
format: 
    html:
        page-layout: full
        margin-left: 0.5em
        margin-right: 0.5em
        css: style.css
        number-sections: true
        number-depth: 1
        toc: true           # table of content
        toc-location: left # table of content on the right
        toc-title: "Table of Content"   # table of content title
    # pdf:
    #     geometry:
    #         - top=18px
    #         - bottom=18px
    #         - left=18px
    #         - right=18px
    #     css: style.css
    #     number-sections: true
---

<!-- 
Blues/Greys: steelblue, royalblue, dodgerblue, slategray, darkslateblue.
Greens:      seagreen, forestgreen, olive, darkolivegreen.
Reds/Pinks:  crimson, indianred, firebrick, salmon.
Earth Tones: sienna, peru, chocolate, goldenrod. 
-->

# Foreword

It is a shame that we have only one semester to learn so much new knowledge but we don't have a real opportunity to really develop a meaningful and serious project.

## Ultimate goal

In this assignment, we aim to build a mini-library that mimic two important machine learning frameworks in the machine learning world. In fact, they look ridiculously simple, they are one of the backbones of vast number of machine learning frameworks that have been used these days, including of course the genAI frameworks you are deploying. In the end of the assignment, we try to mimic two important classes provided in the celebrated library for machine learning: [**scikit-learn** -- Text contains hyperref](https://scikit-learn.org/stable/). Particularly, we focus on two regression models

- Linear Regression
- Logistic Regression

## Objectives
The two main objectives of this assignment consists of

1. Develop a mini-library `sklearn_lite` that mimic a small part of the Python library scikit-learn
2. Apply our built library to perform some fancy applications.

Besides these two main objectives, we take this opportunity to learn some knowledge that could be useful for you when you may choose [ENG4200](https://www.gla.ac.uk/coursecatalogue/course/?code=ENG4200) and [ENG5337](https://www.gla.ac.uk/coursecatalogue/course/?code=ENG5337)

# Quick tour to the world of machine learning

<!-- ## Intro and examples -->
As mentioned above, we will develop two classes `LinearRegression` and `LogisticRegression` representing two basic regression models "Linear Regression" and "Logistic Regression", respectively.

- [**Linear Regression.**]{style="color:royalblue"} is used to make prediction on the continous spectrum of data points.

    **Examples**

    - Predict the house price of a given flat given its features such as total living area, number of bedrooms, distance to the city center, distance to schools, distance to public transporation stations, $\ldots$
    - Predict the age of a person by using their recent photos.
    - Predict the price of a bottle of wine given its information about the wine: number of years, location, type of grapdes, $\ldots$
  
    **Linear regression** can be easily extended to **Polynomial Regression** to enhance its power and widen its capability in various complex applications. 
- [**Logistic Regression**]{style="color:royalblue"} is used to classify data points into finite number of categories, such as $0, 1, 2, \ldots, K$.

    **Examples**
    - Given an image of one digit written by hand, predict what number it represents. The image represent $1$ out of $10$ digits: $0, 1, 2, \ldots, 9$.
    - Given a patient's record of ECG diagram, predict whether the patient is fine or not, i.e., just $0$ (not sick) or $1$ (sick).

## Terminologies

Before going into the mathematics behind these two machine learning models, we need some terminologies. 

- [**Supervised Learning**]{style="color:crimson"}

    Both of these regression methods are classified as **supervised learning** methods in which we have the input data given by $\mathbf{x}^{(i)} = (x_1^{(i)}, x_2^{(i)}, \ldots, x_n^{(i)})$ and output data given by $y^{(i)}$ for $i = 1, \ldots, m$, where $m$ is the number of samples.

- [**Dataset**]{style="color:crimson"}

    Assume that we are given a dataset $\mathcal{D}$ with $m$ [**samples**]{style="color:royalblue"}, each sample has $n$ input [**features**]{style="color:royalblue"} $\mathbf{x}^{(i)}=(x_1^{(i)}, \ldots, x_n^{(i)}) \in \mathbb{R}^{n}$ and $m$ label $y^{(i)}$, where $i \in \{1, \ldots, m\}$ is an index of one sample. So the dataset $\mathcal{D}$ can be written as follows

    $$
    \mathcal{D} = \Big\{ (\mathbf{x}^{(1)}, y^{(1)}), (\mathbf{x}^{(2)}, y^{(2)}), \ldots, (\mathbf{x}^{(m)}, y^{(m)}) \Big\}
    $$

- [**Regression Problem versus Classification Problem**]{style="color:crimson"}

    - In the world of machine learning \& statistics, a [**regression problem**]{style="color:royalblue"} is a task where the goal is to predict a **continuous, numerical output value** based on one or more input variables (features).
    - In a [**classification problem**]{style="color:royalblue"}, the goal is to predict a **discrete label** or **category** for a given input. Instead of calculating "how much" (like a price), you are determining "which one" (like a species or a status).

- [**Linear regression**]{style="color:crimson"}

    In [**regression problem**]{style="color:royalblue"} the label $y^{(i)}$ is a real number: $y^{(i)} \in \mathbb{R}$. An example is given in the dataset `concrete.csv`.

    ```{.python}
    import pandas as pd
    concrete_data = pd.read_csv("./data/concrete.csv")
    n_samples = len(concrete_data)
    print(f"Number of samples = {n_samples}")   # the first row (headers of data) not counted
    concrete_data.head()
    ```
    In this dataset, we use $8$ input features are used to make prediction, that is $\mathbf{x}^{(i)} \in \mathbb{R}^{8}$. The label $y^{(i)}$ is a scalar (real) number, i.e. $y^{(i)} \in \mathbb{R}$.

    &#10149; **Note**&nbsp; Do not confuse "_regression problem_" with "_linear regression_" model. Linear regression is a mathematical model, while regression problem refers to a class of problems of predicting contiuous outputs.

- [**Logistic regression**]{style="color:crimson"}

    In [**classification problem**]{style="color:royalblue"} the label $y^{(i)}$ is an integral number (integer type) and it takes only finite number of values. If the problem involves classification of samples into $K$ categories, the value of $y^{(i)}$ can take only $K$ possibilities: $y^{(i)}\in \{0, \ldots K - 1\}$. Apparently, it does not matter how you set the value for $y^{(i)}$ as long as there are only $K$ possible values. However, it is conventional to start from $0$ and then increase by $1$. The mathematics stay the same; just formality of how you name things. An example is given in the dataset `ecg.csv`

    ```{.python}
    import numpy as np
    data = np.loadtxt('./data/ecg.csv', delimiter=',')
    X = data[:,:-1] # take all the rows, all the column from the first to the second last
    y = data[:,-1]  # take all the rows, the last column
    n_features = X.shape[1]
    n_classes = len(np.unique(y))
    print(f"n_features = {n_features}")
    print(f"n_classes = {n_classes}")
    ```

    As this is the ECG diagram, let us draw them and show the label as on the figure title as well.

    ```{.python}
    import matplotlib.pyplot as plt
    nrows, ncols = 2, 4
    plt.figure(figsize=(8, 3.5))
    np.random.seed(seed=42)         # just for reproducibility purpose
    for i in range(nrows * ncols):
        plt.subplot(nrows, ncols, i+1)
        idx = np.random.randint(low=0, high=X.shape[0])
        plt.plot(data[idx])
        plt.title(f"label = {int(y[idx])}")
        plt.xticks(np.linspace(0, 120, 5))
        plt.grid(True)
        
    plt.tight_layout()
    ```

## Build a polynomial regression model

In this example, we generate a dataset with one single feature by adding noise to data points created on the graph of a cubic function
$$
p(x) = x (x - 1)(x + 1) = x^3 - x
$$

```{python}
import numpy as np
import matplotlib.pyplot as plt
np.random.seed(42)
n_samples = 100
poly = lambda x: x * (x - 1) * (x + 1)
x = np.random.uniform(-1.5, 1.5, n_samples)
y_true = poly(x)
noise = np.random.normal(0, 0.2, size=n_samples) * y_true
y = y_true + noise
xx = np.linspace(-1.5, 1.5, 1000)

plt.figure(figsize=(4, 2.5))
plt.plot(xx, poly(xx))
plt.scatter(x, y, marker='x', c='k', s=6)
plt.grid(True)
```

As we can see, at this point we have the dataset
$$
\mathcal{D} = \Big\{(x^{(1)}, y^{(1)}), \ldots, (x^{(m)}, y^{(m)}) \Big\}
$$
with $x^{(i)} \in \mathbb{R}$. Apparently, if we try to fit a line to this dataset, the fitting line has no chance to really fit the data well. One cannot "fit" a straight line to a curve. To build a model that fits this kind of data, we apparently that the following function will do a pretty good job
$$
f_{\mathbf{w}, b}(\mathbf{x}) = w_1 x + w_2 x^2 + w_3 x^3 + b = \mathbf{w}\cdot \mathbf{x} + b,
$$ {#eq-cubic-regression-model}
where
$$
\mathbf{w} = (w_1, w_2, w_3), \quad \mathbf{x} = (x, x^2, x^3).
$$
You should see immediately from the equation @eq-cubic-regression-model that "[Wait a minute](https://www.youtube.com/watch?v=cw9FIeHbdB8)", that's exactly a linear regression model with $3$ features, each feature $x_j$ is formed by taking the original feature $x$ to power $j$. That is, we have $x_1 = x^{1}, x_2 = x^{2}, x_{3} = x^3$.

It is very easy to form these features in NumPy. Fortunately, scikit-learn gives us a tool to do this too. In the following code, the feature $x^{0} = 1$ is also added to the matrix `X_poly`.
```{python}
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree=3)
X = x.reshape((-1, 1))
X_poly = poly.fit_transform(X)
print(f"X_poly =\n{X_poly[:6]}") # print the first 5 samples
print(f"X_poly.shape = {X_poly.shape}")
```


# Deploying `LinearRegression` and `LogisticRegression`

Before we discuss the mathematics behind Linear Regression and Logistic Regression, let us examine two examples given in the two above-mentioned files `concrete.csv` and `ecg.csv`. We first write a Python program to make prediction of concrete strength and then another program to make prediction whether a patient is fine or not given their ECG data.

## Linear regression using `LinearRegression`

We shall study two applications of `LinearRegression`

- Predict the concrete strength using $8$ features of technical info of the concrete.
- Build a simple polynomial prediction model.

### Predict the strength of concrete
First, we need to load data using the library Pandas and then convert the data into `ndarray`.
```{.python}
import pandas as pd
import numpy as np
concrete_data = pd.read_csv("./data/concrete.csv") # concrete_data is a DataFrame object
concrete_data = concrete_data.to_numpy()    # now, it is a ndarray object
print(concrete_data)
```

You will learn soon that we need to test whether our prediction model is good or not. However, all the data we have are only avaliable in the `csv` file. For this reason, machine learning practioners normally split the dataset into two sets: **training set** and **test set**. The training set is used to train the machine learning model, which means seeking the model parameters $\mathbf{w}$ and $b$ explained in Assignment 1. In our project, we don't have to training-test split when we build the library. I just want to explain the point.
```{.python}
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)
```

Training the model by using scikit-learn is ridiculously easy as all the power-lifting has been done by the library.
```{.python}
model = LinearRegression()  # define a LinearRegression model
model.fit(X_train, y_train) # training happens here -- look for model parameters w, b
```

As explained above, we measure how good our prediction model is by compute $R^2$ (read R-squared) score on both the training set and the test set. The $R^2$ score being close to $1$ means the model predicts extremely well, the score being close to $0$ means the model predicts extremely bad. Note that $R^2$ score can be negative -- The square term may be misleading you to think that it must be a non-negative number.
```{.python}
train_r2_score = r2_score(y_true=y_train, y_pred=model.predict(X_train))
test_r2_score = r2_score(y_true=y_test, y_pred=model.predict(X_test))
print(f"Training R^2 Score: {train_r2_score:.4f}")
print(f"    Test R^2 Score: {test_r2_score:.4f}")
```
According to these R-squared score, the model has done a pretty good job in predicting the concrete strength given $8$ input features.

## Logistic regression using `LogisticRegression`

As before, we need to load the csv file into an `ndarray` to prepare the data for training the logistic regression model.
```{.python}
data = pd.read_csv("./data/ecg.csv")
data = data.to_numpy()
# Plot some of the data for better understanding
nrows, ncols = 2, 5
plt.figure(figsize=(9, 3.0))
np.random.seed(seed=42)         # just for reproducibility purpose
for i in range(nrows * ncols):
    plt.subplot(nrows, ncols, i+1)
    idx = np.random.randint(low=0, high=X.shape[0])
    plt.plot(data[idx])
    plt.title(f"label = {int(y[idx])}")
    plt.xticks(np.linspace(0, 120, 5))
    plt.grid(True)
    
plt.tight_layout()
```

Next, we split the original dataset into two sets: training set and test set. We can use any splitting proportion we want. Here, we split $80\% - 20\%$ as above.
```{.python}
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)
```

Now, we define a `LogisticRegression` model object and perform the training
```{.python}
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)
```

Unlike regression problems in which we can measure how well the model is by using $R^2$ score, we cannot use this score to measure how well the model performs on classification problem. Instead, we use the `accuracy_score` to measure how accurate the model can classify the samples into the right category. In our case, we measure how well the model can predict the samples in the test set. The score is just simply the number of correct predictions divided by the total number of predictions made.

```{.python}
from sklearn.metrics import accuracy_score
y_pred = log_reg.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Model accuracy: {accuracy: .4f}")
```

The model can make prediction fantastically, almost $99\%$ correctly. Now, we plot some data in the test set and show both the prediction as well as the ground truth label (the labels that are given by the data).
```{.python}
nrows, ncols = 2, 3
plt.figure(figsize=(9, 4.8))
np.random.seed(seed=42)         # just for reproducibility purpose
for i in range(nrows * ncols):
    plt.subplot(nrows, ncols, i+1)
    
    idx = np.random.randint(low=0, high=X_test.shape[0])
    actual_label = int(y_test[idx])
    # convert this to a row vector which is a (1 x n) matrix.
    data_point = X_test[idx].reshape(1, -1)     
    predicted_label = int(log_reg.predict(data_point)[0])

    plt.plot(X_test[idx])
    plt.title(f"Actual Label: {actual_label} -- Pred: {predicted_label}")
    plt.xticks(np.linspace(0, 120, 5))
    plt.grid(True)
    
plt.tight_layout()
```


# Mathematics behind the scene

Since we want to implement these models in C++ from scratch, we need to understand the mathematics behind the scene. This is the topic of this Section. Note that you have learned the maths behind `LinearRegression` in the Assignment \#1. We shall revisit it and proceed to logistic regression. You will soon recognize that although the mathematical formulation behind the logistic regression model is slightly different from that of linear regression model, the gradient descent iteration algorithm shares exactly the same formulation. For this reason, a large portion of what you have done for linear regression can easily carried over to logistic regression.