---
title: "Mathematics behind Linear Regression and Logistic Regression"
# subtitle: "C++ Object-oriented Programming"
author:
    Khiem Nguyen 
    <br> Lecturer in Multiscale Materials
    <br> <khiem.nguyen@glasgow.ac.uk>
author-meta: "Lecturer in Multiscale Materials"
jupyter: false
execute: 
  eval: true
format: 
    html:
        output-file: "maths.html"
        embed-resources: true
        grid:
            body-width: 1600px
            margin-width: 20px
            sidebar-width: 200px
        # page-layout: full
        # margin-left: 0.5em
        # margin-right: 0.5em
        code-fold: true
        css: style.css
        number-sections: true
        number-depth: 3
        toc: true               # table of content
        toc-location: left      # table of content on the left
        toc-title: "Table of Content"   # table of content title

    # pdf:
    #     embed-resources: true
    #     geometry:
    #         - top=24px
    #         - bottom=24px
    #         - left=36px
    #         - right=36px
    #     css: style.css
    #     number-sections: true
    #     number-depth: 3
    #     colorlinks: true
---

**Equations from main file `assignment_02.html`**

**General Dataset**

We are given a dataset $\mathcal{D}$ with $m$ samples and each sample has $n$ input features $\mathbf{x}^{(i)} = (x_1^{(i)}, \ldots, x_n^{(i)}) \in \mathbb{R}^{n}$ and one output label $y \in \mathbb{R}^{n}$.

$$
\mathcal{D} = \Big\{ \big( \mathbf{x}^{(1)}, y^{(1)} \big), \big( \mathbf{x}^{(2)}, y^{(2)} \big), \ldots, \big( \mathbf{x}^{(m)}, y^{(m)} \big) \Big\}
$$ {#eq-dataset}

**Gradient Descent Update Formla**

The gradient descent method is given by the following iteration formula. The variable $\Theta$ corresponds to the model parameters, which are the learnable parameters of the model. The learning rate $\alpha$ is a positive scalar hyperparameter that controls the step size of each iteration.

$$
\Theta^{[t+1]} := \Theta^{[t]} - \alpha \nabla \mathcal{L}(\Theta^{[t]}),\quad \forall t= 0, 1, 2, \ldots
$${#eq-gradient-descent-update-formula}

# Linear Regression with multiple features: Theory

In this section, we study:

- Description of a regresison problem
- Linear regression model
- Loss function for training the linear regression model
- Gradient of loss function

## Problem description {#linear-regression-problem-description}

We are given a dataset $\mathcal{D}$ with $m$ samples and each sample has $n$ input features $\mathbf{x}^{(i)} = (x_1^{(i)}, \ldots, x_n^{(i)}) \in \mathbb{R}^{n}$ and one output label $y \in \mathbb{R}^{n}$ -- see @eq-dataset again
$$
\mathcal{D} = \Big\{ (\mathbf{x}^{(1)}, y^{(1)}), (\mathbf{x}^{(2)}, y^{(2)}), \ldots, (\mathbf{x}^{(m)}, y^{(m)}) \Big\}
$${#eq-dataset-D}

This dataset can be written in two matrices
$$
\mathbf{X} = \begin{bmatrix}
x_1^{(1)} & x_{2}^{(1)} & \ldots & x_{n}^{(1)} \\[3pt]
x_1^{(2)} & x_{2}^{(2)} & \ldots & x_{n}^{(2)} \\[3pt]
\vdots & \vdots & \ddots & \vdots & \\[3pt]
x_1^{(m)} & x_{2}^{(m)} & \ldots & x_{n}^{(m)}
\end{bmatrix}, \qquad 
\mathbf{y} = \begin{bmatrix} y_{\phantom{1}}^{(1)} \\[3pt]
y_{\phantom{1}}^{(2)} \\[3pt]
\vdots \\[3pt]
y_{\phantom{1}}^{(m)}
\end{bmatrix}
$$ {#eq-dataset-matrix-presentation}

Our task is to build a model, which is actually just a function or a mapping, to predict a new output $\widehat{y}$ given a new sample (data point) $\mathbf{x}$. That is we need to construct the function $f = f(\mathbf{x})$ so that it fits the data very well. If the model can be visualized, we expect the graph $y = f(\mathbf{x})$ should fit the data points in the high-dimensional space $\mathbf{R}^{n + 1}$ very well. Now, we go through three steps mentioned in section "Build and Train ML models"

## Linear regression model
The linear regression model is defined by a simple linear relationship between input $\mathbf{x}$ and output $y$:
$$
\widehat{y} = f_{\mathbf{w}, b}(\mathbf{x})= \mathbf{w}\cdot \mathbf{x} + b.
$$
The parameters $\mathbf{w} = (w_1, \ldots, w_n)$ are called **weights** and the parameter $b$ is called **bias**. This linear regression model is fully determined by the [**learnable parameters**]{style="color:blueviolet"} $\mathbf{w}=(w_1, \ldots, w_n)$ and $b$. [**Our objective**]{style="color:gray"} is to seek these _learnable parameters_ $w_1, \ldots, w_n$ and $b$.

## Loss function

To measure how well the model is, we use the [**Mean Square Error**]{style="color:royalblue"} (MSE) loss function:
$$
\begin{aligned}
\mathcal{L}(\mathbf{w}, b) &= \frac{1}{m} \sum\limits_{i=1}^{m}(\widehat{y} \big(\mathbf{x}^{(i)}) - y^{(i)} \big)^2 =  \frac{1}{m} \sum\limits_{i=1}^{m} \big(f_{\mathbf{w},b}(\mathbf{x}^{(i)}) - y^{(i)} \big)^2 \\
&= \frac{1}{m} \sum\limits_{i=1}^{m} \big(\mathbf{w}\cdot \mathbf{x}^{(i)} + b - y^{(i)} \big)^2
\end{aligned}
$$ {#eq-mean-square-error-loss}

Note that we don't use $2m$ in the denominator as in the Assignment 01. This is just to prove that the minimium point is exactly the same, only the minimum value is scaled by a factor $1/2$. For this reason, the gradient $\nabla \mathcal{L}$ will be also scaled (see below).

It is immediately clear that the loss function $\mathcal{L}$ defined as above is just a function of $\mathbf{w}$ and $b$ because the values $\mathbf{x}^{(i)}$ and $y^{(i)}$ for all $i = 1, \ldots, m$ are given in the dataset $\mathcal{D}$ (e.g., in the `.csv` file).

We recall here "training the model" means "looking for $\mathbf{w}$ and $b$" and the way to do this is to implement the gradient descent method given by the iteration formula @eq-gradient-descent-update-formula. In the current case, the variable $\Theta$ corresponds to the model parameters $\mathbf{w}$ and $b$. To implement the update rule given by @eq-gradient-descent-update-formula, we need to compute the gradient $\nabla\mathcal{L}$ which refers to derivatives of $\mathcal{L}$ with respect to $w_1, w_2, \ldots, w_n$ and to $b$:
$$
\nabla \mathcal{L} = \bigg(\frac{\partial \mathcal{L}}{\partial w_1}, \cdots, \frac{\partial \mathcal{L}}{\partial w_n}, \frac{\partial \mathcal{L}}{\partial b} \bigg)
$$

Therefore, we need to compute the gradient of the loss function $\nabla\mathcal{L}$ to perform the gradient descent iteration algorithm.

## Gradient of loss function

The gradient of $\mathcal{L}$ given by @eq-mean-square-error-loss is computed as follows^[You can try to carry out the derivation. It is surprisingly easy to be honest. Clever students like you will definitely do this 😏😏] -- If you are interested in the derivation, please refer `derivation.html`.
$$
\begin{aligned}
\frac{\partial \mathcal{L}}{\partial w_1} &= \frac{2}{m} \sum\limits_{i=1}^{m} \big(\widehat{y}(\mathbf{x}^{(i)}) - y^{(i)} \big) x_{1}^{(i)} \\[3pt]
& \text{so on} \\[3pt]
\frac{\partial \mathcal{L}}{\partial w_n} &= \frac{2}{m} \sum\limits_{i=1}^{m} \big(\widehat{y}(\mathbf{x}^{(i)}) - y^{(i)} \big) x_{n}^{(i)} \\[3pt]
\frac{\partial \mathcal{L}}{\partial b} &= \frac{2}{m} \sum\limits_{i=1}^{m} \big(\widehat{y}(\mathbf{x}^{(i)}) - y^{(i)} \big) \cdot 1 \\[3pt]
\end{aligned}
$$
Note that since we have $m$ instead of $2m$ in the denominator of @eq-mean-square-error-loss, the gradient is also scaled, and thus we see number $2$ in the nominator of $\frac{2}{m}$ as compared to $\frac{1}{m}$ in the Assignment 01. By plugging these equations in @eq-gradient-descent-update-formula, we obtain the following update rule
$$
\begin{aligned}
w_1^{[t+1]} &:= w_{1}^{[t]} - \frac{2}{m} \sum\limits_{i=1}^{m} \big[\big(\mathbf{w}^{[t]} \cdot \mathbf{x}^{(i)} + b^{[t]}\big) - y^{(i)} \big] x_{1}^{(i)} \\[3pt]
& \text{so on} \\[3pt]
w_n^{[t+1]} &:= w_{n}^{[t]} - \frac{2}{m} \sum\limits_{i=1}^{m} \big[\big(\mathbf{w}^{[t]} \cdot \mathbf{x}^{(i)} + b^{[t]}\big) - y^{(i)} \big] x_{n}^{(i)} \\[3pt]
b^{[t+1]} &:= b^{[t]} - \frac{2}{m} \sum\limits_{i=1}^{m} \big[\big(\mathbf{w}^{[t]} \cdot \mathbf{x}^{(i)} + b^{[t]}\big) - y^{(i)} \big] \cdot 1\\[3pt]
\end{aligned}
$$

## Numerical Example


[**The Black Box Trap**]{style="color:royalblue"}&nbsp; In modern engineering and physics, it is easy to feed parameters into a simulation or a Python script and get a result. However, this normally leads to the feeling that "we understand it" while in reality "we don't quite really understand it."

:::{.callout-tip}
In **MIT** or **CalTech** you will frequently hear professors and Teaching Assitants reiterate some version of "[If you cannot solve it for $n = 2$, you don't understand the general case.]{style="color:red"}"
:::

For this reason, let us go through all the theoretical steps above using a simple $2$-dimensional example with $4$ samples. Note that with only $3$ points, we can always build a plane that go through all $3$ points. Thus, we chose $4$ points.


[**Dataset**]{style="color:royalblue"}

For reproducibility purpose, we design the dataset by using the exact/reference linear regression model:

$$
f(x_1, x_2) = \frac{1}{2} x_1 - \frac{1}{2} x_2 + \frac{3}{2}
$${#eq-reference-linear-regression-model}

The dataset is given by the following table

| $x_1$ | $x_2$ | $y$ |
|:--|:--|:--|
| $0$ | $0$ | $3/2$ |
| $1$ | $0$ | $2$ | 
| $0$ | $1$ | $1$ |
| $1$ | $1$ | $v$ |

We keep the label value of the last data point general, denoted by $v$. We shall see that by adjusting $v$, the loss function will also change and the minimum point is not always equal to $0$.

### Hand-written calculation


[**Linear Regression Model**]{style="color:royalblue"}

In this example, we have $2$ features. The linear regression model for $2$ input features reads
$$
\widehat{y} = f_{\mathbf{w}, b}(x_1, x_2) = w_1 x_1 + w_2 x_2 + b.
$$

[**Loss Function**]{style="color:royalblue"}

We reiterate the formula for the loss function
$$
\begin{aligned}
\mathcal{L}(w_1, w_2, b) &= \frac{1}{4} \sum_{i=1}^{4} \big(\hat{y}^{(i)} - y^{(i)} \big)^2 = \frac{1}{4}\sum\limits_{i=1}^{4} \big[ e^{(i)} \big]^2 \\[3pt]
&= \frac{1}{4} \sum\limits_{i=1}^{4}\Big( w_1 x_1^{(i)} + w_2 x_2^{(i)} + b - y^{(i)} \Big)^2 
\end{aligned}
$${#eq-loss-function-linear-regression-example-model}

where the error term $e^{(i)}$ is defined by
$$
\begin{aligned}
e^{(i)} &= \widehat{y}^{(i)} - y^{(i)} = f_{\mathbf{w}, b}(\mathbf{x}^{(i)}) - y^{(i)} \\[3pt]
&= w_1 x_1^{(i)} + w_2 x_2^{(i)} + b - y^{(i)}.
\end{aligned}
$$

For the dataset with $m=4$ samples, we calculate the individual squared errors by direct substitution:
$$
\begin{aligned}
\text{For } (0, 0, 3/2) &: e^{(1)} = (b - 3/2) \\[6pt]
\text{For } (1, 0, 2)  &: e^{(2)} = (w_1 + b - 2) \\[6pt]
\text{For } (0, 1, 1)  &: e^{(3)} = (w_2 + b - 1) \\[6pt]
\text{For } (1, 1, v)  &: e^{(4)} = (w_1 + w_2 + b - v)
\end{aligned}
$$

Substituting these expressions for $e^{(i)}$ into @eq-loss-function-linear-regression-example-model, we arrive at the total loss function
$$
\mathcal{L}(w_1, w_2, b) = \frac{1}{4} \bigg[ \left(b - \frac{3}{2}\right)^2 + 
    (w_1 + b - 2)^2 + (w_2 + b - 1)^2 + (w_1 + w_2 + b - v)^2  \bigg]
$$

[**Note**]{style="color:crimson"}&nbsp; It is clear that no matter how complicated the dataset is, the loss function for linear regression models is a quadratic function with respect to the model parameters. In this case, $\mathcal{L}$ is a quadratic function of $(w_1, w_2, b)$. For this reason, there exists one and only one minimal point $\mathcal{L}$, which is computed by solving the equation $\nabla \mathcal{L} = 0$.

[**Gradient of the Loss Function**]{style="color:royalblue"}

The mimization of $\mathcal{L}$ can be obtained by solving the equation $\nabla \mathcal{L} = 0$, namely the equations retrieved by setting the partial derivative of $\mathcal{L}$ with respect to all the variables to $0$. In this case, it simply reads
$$
\nabla\mathcal{L} = 0\quad\Leftrightarrow \quad \left\{\begin{aligned}
\frac{\partial \mathcal{L}}{\partial w_1} &= 0, \\[3pt]
\frac{\partial \mathcal{L}}{\partial w_1} &= 0, \\[3pt] 
\frac{\partial \mathcal{L}}{\partial b} &= 0\end{aligned} \right.
$${#eq-optimality-condition}

We can easily derive
$$
\begin{aligned}
\frac{\partial \mathcal{L}}{\partial w_1} &= \frac{1}{2} \left[ (w_1 + b - 2) + (w_1 + w_2 + b - v) \right], \\[3pt]
\frac{\partial \mathcal{L}}{\partial w_2} &= \frac{1}{2} \left[ (w_2 + b - 1) + (w_1 + w_2 + b - v) \right], \\[3pt]
\frac{\partial \mathcal{L}}{\partial b} &= \frac{1}{2} \left[ (b - 1.5) + (w_1 + b - 2) + (w_2 + b - 1) + (w_1 + w_2 + b - v) \right]
\end{aligned}
$$

Then, we obtain a system of $3$ equations for $3$ **learnable parameters** $w_1, w_2, b$. The three equations given by the optimality condition @eq-optimality-condition have one single solution:

$$
w_1 = \frac{2v - 1}{4}, \quad w_2 = \frac{2v - 5}{4}, \quad b = \frac{15 - 2v}{8}
$${#eq-minimal-point-linear-regression-example-model}

[**Discussion on the loss function**]{style="color:royalblue"}

By substituting @eq-minimal-point-linear-regression-example-model into the loss function @eq-loss-function-linear-regression-example-model, we obtain the minimum of the loss function -- note that this minimum value still depends on $v$ because we allow the forth data points to move freely in the $y$-axis with value $v$:

Substituting the optimal parameters back into the error terms (without being squared here):
$$
\begin{aligned}
    e^{(1)} &= \left(\frac{2v - 1}{4}\right) \cdot 0 + \left(\frac{2v - 5}{4}\right) \cdot 0 + \left( \frac{15 - 2v}{8}\right) - \frac{3}{2}  = \frac{3 - 2v}{8} \\
    e^{(2)} &= \left(\frac{2v - 1}{4}\right) \cdot 1 + \left(\frac{2v - 5}{4}\right) \cdot 0 +  \left(\frac{15 - 2v}{8}\right) - 2 = \frac{2v - 3}{8} \\
    e^{(3)} &= \left(\frac{2v - 1}{4}\right) \cdot 0 + \left(\frac{2v - 5}{4}\right) \cdot 1 + \left(\frac{15 - 2v}{8}\right) - 1 = \frac{2v - 3}{8} \\
    e^{(4)} &= \left(\frac{2v - 1}{4}\right) \cdot 1 + \left(\frac{2v - 5}{4}\right) \cdot 1 + \left(\frac{15 - 2v}{8}\right) - v = \frac{3 - 2v}{8}
\end{aligned}
$$

The loss function evaluates to
$$
\mathcal{L}_{\text{min}} = \frac{1}{4}\sum\limits_{i=1}^{4} \big[e^{(i)}\big]^2 = \frac{(2v - 3)^2}{64}
$$

:::{.callout-note}
**The minimum of a loss function does not need to be zero**
:::

As we can see the minimal loss function $\mathcal{L}_\text{min}$ can be non-zero depending on $v$. The next legitimate question is that what it implies when $\mathcal{L}_\text{min} = 0$. Let us think of this scenario. 

The loss function measures how well our prediction model makes prediction on the seen/given data. The zero loss function implies that the model has made perfect prediction on the seen/given dataset because all the error terms $e^{(i)}$ must be equal to zero for this to occur. As a consequence, all the data points sit perfectly on the graph of the function 
$$
(G): \quad y = f_{\mathbf{w}, b}(\mathbf{x}) = w_1 x_1 + w_2 x_2 + b.
$$ 

For a dataset of $3$ data points, we can always construct a plane going through all the data points regardless of the actual values of the data points. This is no longer the case for $4$ data points. When $v = 3/2$, the minimum of loss function is equal to zero, $\mathcal{L}_{\text{min}} = 0$. In this case, the 4th data point is given by $(1, 1, 3/2)$, which sits perfectly on the graph -- see the reference model @eq-reference-linear-regression-model

$$
y = \widehat{f}(x_1, x_2) = \frac{1}{2}x_1 - \frac{1}{2}x_2 + \frac{3}{2} 
$$

because $y^{(4)} = \widehat{f}(x_1^{(4)}, x_2^{(4)})$:
$$
\frac{3}{2} = \frac{1}{2} \cdot 1 - \frac{1}{2} \cdot 1 + \frac{3}{2}
$$

### Python implementation using symbolic computation

Instead of computing the loss function by hand, I take this opportunity to introduce you to a useful library in Python: [SymPy](https://www.sympy.org/). To this end, please just follow the code snippet. The code is quite easy to understand.

First of all, you need to activate the conda environment or the virtual environment and then install `sympy` by using one of the following towo command lines:

:::{.columns}

:::{.column width="40%"}
```{bash}
conda install sympy
```
:::
:::{.column width="40%"}
```{bash}
pip install sympy
```
:::

:::

[**Compute loss function**]{style="color:royalblue"}

As the starting point, we setup the dataset, define the linear regression model and compute the loss function with the help of symbolic calculation by `sympy` library.

```{python}
import sympy as sp

# Define symbols
w1, w2, b, v = sp.symbols('w1 w2 b v')

# Define the dataset (x1, x2, y)
data = [(0, 0, 3/2), (1, 0, 2), (0, 1, 1), (1, 1, v)]

def model(x1_val, x2_val):
    return w1 * x1_val + w2 * x2_val + b

# Compute the sum of squared errors
squared_errors = []
for x1_val, x2_val, y_val in data:
    pred = model(x1_val, x2_val)    # compute prediction using the model.
    squared_err = (pred - y_val)**2       
    squared_errors.append(squared_err)

n_samples = len(data)
loss_function = 1 / (n_samples) * sum(squared_errors)

# Display results
def prettify(text: str, n_dashes=30, char="="):
    long_dash = n_dashes*char
    print("\n" + long_dash + "\n" + text + "\n" + long_dash)

prettify("Symbolic Loss Function")
sp.pprint(loss_function)
```

[**Compute gradient of loss function and optimal parameters of the linear regression model**]{style="color:royalblue"}

Next, we solve the equation $\nabla \mathcal{L} = 0$ for the "learnable parameters", namely the model parameters $(w_1, w_2, b)$. The results are printed for comparison with hand calculation above. 

:::{.callout-tip}
In fact, I used the results obtained by Python to write down the hand-written computation.
:::

```{python}
# Compute the gradients
grad_w1 = sp.diff(loss_function, w1)
grad_w2 = sp.diff(loss_function, w2)
grad_b = sp.diff(loss_function, b)

grad = [("dL/dw1", grad_w1), ("dL/dw2", grad_w2), ("dL/db", grad_b)]
prettify(f"Gradient of the Loss Function")
for deriv, expr in grad:
    print(f"{deriv} = {expr}") 

# Solve the system gradient-of-loss = 0
solution = sp.solve([grad_w1, grad_w2, grad_b], (w1, w2, b))

prettify(f"Optimized model parameters")
for param, expr in solution.items():
    print(f"{param} = {expr}")
```

[**Compute minimum of loss function**]{style="color:royalblue"}

By direct substitution of the solution obtained above into the loss function `loss`, we can compute the minimum of the loss function

```{python}
# Substitute the solution for w1, w2, b into loss function
min_loss = loss_function.subs(solution)
min_loss_simplified = sp.simplify(min_loss)

prettify(f"Min of loss function")
print(f"L_min = {min_loss_simplified}")

# Solve L_min = 0 for v
vhat = sp.solve(min_loss_simplified, v)[0]
print(f"v (for L_min = 0): {vhat:.3f}")
```

[**Visualization**]{style="color:royalblue"}

Let us visualize the results.

```{python}
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

def plot_regression_3d(v_val, ax, title):
    # Data points
    x1_data = np.array([0, 1, 0, 1])
    x2_data = np.array([0, 0, 1, 1])
    y_data  = np.array([1.5, 2, 1, v_val])

    # Optimal parameters (derived from grad L = 0)
    w1 = (2 * v_val - 1) / 4
    w2 = (2 * v_val - 5) / 4
    b  = (15 - 2 * v_val) / 8

    # 3. Create grid for the plane
    x1_range = np.linspace(-0.2, 1.2, 20)
    x2_range = np.linspace(-0.2, 1.2, 20)
    X1, X2 = np.meshgrid(x1_range, x2_range)
    Y_plane = w1 * X1 + w2 * X2 + b

    surf = ax.plot_surface(X1, X2, Y_plane, alpha=0.4, cmap='viridis', edgecolor='none')
    
    ax.scatter(x1_data, x2_data, y_data, color='red', s=80, depthshade=False, label='Data')

    # Plot residuals (vertical error lines)
    for i in range(len(x1_data)):
        pred = w1 * x1_data[i] + w2 * x2_data[i] + b
        ax.plot([x1_data[i], x1_data[i]], [x2_data[i], x2_data[i]], [y_data[i], pred], 
                color='black', linestyle='--', alpha=0.7)

    # Formatting
    ax.set_title(title, fontsize=14)
    ax.set_xlabel('$x_1$')
    ax.set_ylabel('$x_2$')
    ax.set_zlabel('$y$')
    ax.set_zlim(-2, 3) # Keep scale consistent for comparison

# Create the figure with two subplots
fig = plt.figure(figsize=(4.5, 10))

# Figure 1: v = -1.5 (High Loss)
ax1 = fig.add_subplot(211, projection='3d')
plot_regression_3d(-1.5, ax1, "Linear Regression: $v = -1.5$ (Non-coplanar)")

# Figure 2: v = 1.5 (Zero Loss)
ax2 = fig.add_subplot(212, projection='3d')
plot_regression_3d(1.5, ax2, "Linear Regression: $v = 1.5$ (Perfect Fit)")

plt.tight_layout()
plt.show()
```



# Logistic regression for binary classification

In this section, we study:

- Description of a classification problem
- Logistic regression model
- Loss function for training the logistic regression model
- Gradient of loss function
  

## Problem description

The problem description for a classification problem is quite similar to the description of a regression problem in terms of the given dataset and the ultimate goal prediction, except that the label $y$ is not continous value. Instead, the label $y$ is a discrete value that represents the class membership of the data point. For example, in a binary classification problem, the label $y$ can take values $0$ or $1$, where $0$ represents one class and $1$ represents the other class. The dataset $\mathcal{D}$ is given by @eq-dataset again, but with the understanding that $y^{(i)}$ is a discrete value representing the class label of the $i$-th data point $\mathbf{x}^{(i)}$. The goal of a classification problem is to build a model that can predict the class label of a new data point $\mathbf{x}$, which means we want to construct a function $f = f(\mathbf{x})$ that maps input features to class labels.

**Simple example and reasoning for logistic regression**

Asume we have a dataset of students' study hours and their pass/fail status in a semester. The dataset is given by the following table

| Hours Studied | Pass/Fail (0/1) |
|:--|:--|
| 17 | 0 |
| 18 | 0 |
| 19 | 0 |
| 20 | 0 |
| 21 | 1 |
| 22 | 1 |
| 23 | 1 |
| 24 | 1 |

By looking at the dataset, we can see that there is a clear threshold around 20-21 hours of study. Students who studied less than 21 hours failed (label 0), while those who studied 21 hours or more passed (label 1). If we were to apply linear regression to this dataset, we get a linear line and the decision boundary (where the predicted value is 0.5) would be around 20.5 hours. However, this does not capture the sharp transition from fail to pass that occurs at around 21 hours.

Now, if we introduce outliers: the students who studied 30, 31, 32, and 34 hours and they passed the course with the label 1, the linear regression line would shift significantly, and the decision boundary would move to around 22 hours. This is clearly not desirable as it does not reflect the true nature of the data. Although we call them outliers, they are actually just values that can occur in real life, and thus we need a model that can handle such scenarios without being overly influenced by them. This is where logistic regression comes into play, as it can model the probability of passing as a function of hours studied, and it is less sensitive to outliers compared to linear regression.

```{python}
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

# 1. Dataset
X = np.array([17, 18, 19, 20, 21, 22, 24, 26]).reshape(-1, 1)
y = np.array([0, 0, 0, 0, 1, 1, 1, 1])

# Outliers
outliers = np.array([30, 31, 32, 34]).reshape(-1, 1)
X_with_outlier = np.vstack([X, outliers])
y_with_outlier = np.concatenate([y, [1, 1, 1, 1]])

# 2. Train Models
model_orig = LinearRegression().fit(X, y)
model_outlier = LinearRegression().fit(X_with_outlier, y_with_outlier)

# Calculate X where Y = Threshold (0.5)
# x = (threshold - intercept) / slope
threshold = 0.5
x_bound_orig = (threshold - model_orig.intercept_) / model_orig.coef_[0]
x_bound_outlier = (threshold - model_outlier.intercept_) / model_outlier.coef_[0]

# Plotting
plt.figure(figsize=(10, 6))

# Points
plt.scatter(X[y == 0], y[y == 0], color='blue', label='Class 0 (Fail)', marker='o', s=80)
plt.scatter(X[y == 1], y[y == 1], color='red', label='Class 1 (Pass)', marker='x', s=100, linewidths=2)
plt.scatter(outliers, [1, 1, 1, 1], color='magenta', label='Outlier (30 hrs)', marker='x', s=150, linewidths=3)

# Regression Lines
x_range = np.linspace(0, 32, 100).reshape(-1, 1)
plt.plot(x_range, model_orig.predict(x_range), color='blue', linestyle='--', alpha=0.5, label='LR (Original)')
plt.plot(x_range, model_outlier.predict(x_range), color='red', linestyle='-', label='LR (With Outlier)')

# Threshold and Vertical Decision Boundaries
plt.axhline(0.5, color='gray', linestyle=':', label='Threshold (y=0.5)')
plt.axvline(x_bound_orig, color='green', linestyle='--', label=f'Orig Boundary: {x_bound_orig:.2f}')
plt.axvline(x_bound_outlier, color='magenta', linestyle='-', label=f'Outlier Boundary: {x_bound_outlier:.2f}')

plt.xlabel('Hours Studied')
plt.ylabel('Predicted Value')
plt.title('The Shifted Decision Boundary')
plt.ylim(-0.2, 1.2)
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()
```

::: {.callout-tip}

At this point, you may be wondering why we don't just change the threshold for linear regression to make it work better for classification problems. But we want a model that can make prediction on the unseen data. If we change the threshold and the new data points are added, we must constantly change the threshold, which is not a good solution. This is completely unlogical and not practical. We need a model that can learn from the data and make predictions without us having to manually adjust thresholds.

However, the main reason is that linear regression can produce predicted values outside the range of $0$ and $1$, which does not make sense for probabilities. Logistic regression, on the other hand, uses the logistic function to ensure that the predicted probabilities are always between 0 and 1, making it more suitable for classification tasks.
:::

## Logistic regression model for binary classification

The genius idea of logistic regression is to use the logistic function (also known as the sigmoid function) to model the probability of the positive class (class 1) as a function of the input features. The sigmoid function is defined as follows:
$$
\sigma(z) = \frac{1}{1 + e^{-z}}
$$
It maps any real-valued number into the (0, 1) interval, which can be interpreted as a probability. The logistic regression model for binary classification combines the linear regression model with the sigmoid function to model the probability of class membership. That is, we first compute a linear combination of the input features and then apply the sigmoid function to this linear combination to get the predicted probability of class $1$.

```{python}
import numpy as np
import matplotlib.pyplot as plt
def sigmoid(z):
    return 1 / (1 + np.exp(-z))
x = np.linspace(-10, 10, 100)
plt.figure(figsize=(5, 3))
plt.plot(x, sigmoid(x), label='Sigmoid Function')
plt.axhline(0.5, color='gray', linestyle='--', label='Threshold (0.5)')
plt.xlabel('$z$')
plt.ylabel('$\\sigma(z)$')
plt.title('Sigmoid Function')
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()
```

[**Mathematical formulation**]{style="color:royalblue"}

First, we compute the linear combination of the input features:
$$
z = \mathbf{w} \cdot \mathbf{x} + b
$$
where $\mathbf{w}$ is the weight vector, $\mathbf{x}$ is the input feature vector, and $b$ is the bias term. Then, we apply the sigmoid function to this linear combination to get the predicted probability of class $1$:
$$
\widehat{y} = \sigma(z) = \frac{1}{1 + e^{-z}} = \frac{1}{1 + e^{-(\mathbf{w} \cdot \mathbf{x} + b)}}
$$

## Loss function for training the logistic regression model

We now have a model that can predict the probability of class membership for any given input $\mathbf{x}$. The next step is to define a loss function that we can use to train the logistic regression model by finding the optimal parameters $\mathbf{w}$ and $b$.

We cannot use the mean squared error loss function for logistic regression because it is not suitable for classification problems. Instead, we use the cross-entropy loss function. For one data point, the cross-entropy loss is defined as follows:   
$$
\mathcal{L}(\widehat{y}, y) = \begin{cases}
-\log(\widehat{y}) & \text{if } y = 1 \\
-\log(1 - \widehat{y}) & \text{if } y = 0
\end{cases}
$$

Let us analyse the behavior of this loss function. When $y = 1$, the loss is $-\log(\widehat{y})$. As $\widehat{y}$ approaches $1$, the loss approaches $0$, which is desirable because we want the predicted probability to be close to the true label. However, as $\widehat{y}$ approaches $0$, the loss approaches infinity, which penalizes incorrect predictions heavily. Similarly, when $y = 0$, the loss is $-\log(1 - \widehat{y})$. As $\widehat{y}$ approaches $0$, the loss approaches $0$, and as $\widehat{y}$ approaches $1$, the loss approaches infinity. This behavior encourages the model to make predictions that are close to the true labels.

```{python}
import numpy as np
import matplotlib.pyplot as plt
y = np.linspace(-10, 10, 100)
plt.plot(y, -np.log(sigmoid(y)), label='Loss when $y=1$', linewidth=2)
plt.plot(y, -np.log(1 - sigmoid(y)), label='Loss when $y=0$', linewidth=2)
plt.axhline(0, color='gray', linestyle='--')
plt.xlabel('$y$')
plt.ylabel('Loss')
plt.title('Cross-Entropy Loss for Logistic Regression')
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()
```
We can unify the loss function for both cases ($y=0$ and $y=1$) into a single expression:
$$
\mathcal{L}(\widehat{y}, y) = -\left[ y \log(\widehat{y}) + (1 - y) \log(1 - \widehat{y}) \right]
$$


For a dataset with $m$ samples, we can define the average loss over the entire dataset as follows:
$$
\begin{aligned}
\mathcal{L}(\mathbf{w}, b) &= \frac{1}{m} \sum_{i=1}^{m} \mathcal{L}(\widehat{y}^{(i)}, y^{(i)}) \\[3pt]
&= -\frac{1}{m} \sum_{i=1}^{m} \left[ y^{(i)} \log(\widehat{y}^{(i)}) + (1 - y^{(i)}) \log(1 - \widehat{y}^{(i)}) \right] \\[3pt]
&= -\frac{1}{m} \sum_{i=1}^{m} \left[ y^{(i)} \log\left(\frac{1}{1 + e^{-(\mathbf{w} \cdot \mathbf{x}^{(i)} + b)}}\right) + (1 - y^{(i)}) \log\left(1 - \frac{1}{1 + e^{-(\mathbf{w} \cdot \mathbf{x}^{(i)} + b)}}\right) \right]
\end{aligned}
$$

## Gradient of loss function

As mentioned in the previous section, we can train the logistic regression model by finding the optimal parameters $\mathbf{w}$ and $b$ that minimize the loss function $\mathcal{L}(\mathbf{w}, b)$. To do this, we can use gradient descent, which requires us to compute the gradient of the loss function with respect to the parameters.

The gradient of the loss function with respect to the parameters $\mathbf{w}$ and $b$ can be computed as follows:
$$
\begin{aligned}
\frac{\partial \mathcal{L}}{\partial w_j} &= \frac{1}{m} \sum_{i=1}^{m} \left(\widehat{y}^{(i)} - y^{(i)}\right) x_j^{(i)} \quad \text{for } j = 1, 2, \ldots, n \\[3pt]
\frac{\partial \mathcal{L}}{\partial b} &= \frac{1}{m} \sum_{i=1}^{m} \left(\widehat{y}^{(i)} - y^{(i)}\right)  \cdot 1
\end{aligned}
$$

As compared to the gradient of the loss function for linear regression, the gradient for logistic regression has a similar form, but with the predicted value $\widehat{y}^{(i)}$ being the output of the sigmoid function rather than a linear combination of the input features. This is because the loss function for logistic regression is based on the predicted probabilities, which are obtained by applying the sigmoid function to the linear combination of the input features. For interested readers, you can derive the above expressions for the gradient of the loss function by applying the chain rule of calculus to the loss function $\mathcal{L}(\mathbf{w}, b)$. Detailed derivation can be found in `derivation.html` in the `assignment-02` folder.

[**Update rule for gradient descent**]{style="color:royalblue"}

Once we have the gradient of the loss function, we can update the parameters $\mathbf{w}$ and $b$ using the following update rule for gradient descent:
$$\begin{aligned}
w_j^{[t+1]} &:= w_j^{[t]} - \alpha \frac{\partial \mathcal{L}}{\partial w_j} (\mathbf{w}^{[t]}, b^{[t]}) \quad \text{for } j = 1  , 2, \ldots, n \\[3pt]
b^{[t+1]} &:= b^{[t]} - \alpha \frac{\partial \mathcal{L}}{\partial b} (\mathbf{w}^{[t]}, b^{[t]})
\end{aligned}$$

## Numerical example of logistic regression

Let us come back to the simple example of students' study hours and their pass/fail status. We can apply logistic regression to this dataset to model the probability of passing as a function of hours studied. The logistic regression model will learn the parameters $\mathbf{w}$ and $b$ that best fit the data, and we can use these parameters to make predictions on new data points. We shall compute the loss function and its gradient for this dataset, and then use gradient descent to find the optimal parameters for the logistic regression model. We will also visualize the decision boundary learned by the logistic regression model.

First, the loss function for this dataset can be computed using the formula for the cross-entropy loss. The predicted probabilities $\widehat{y}^{(i)}$ can be computed using the logistic regression model, and then we can substitute these predicted probabilities and the true labels $y^{(i)}$ into the loss function to compute the total loss over the dataset. We can then compute the gradient of the loss function with respect to the parameters $\mathbf{w}$ and $b$, and use this gradient to update the parameters using gradient descent. Finally, we can visualize the decision boundary learned by the logistic regression model to see how well it separates the two classes in the feature space.

$$
\begin{aligned}
\mathcal{L} &= -\frac{1}{8} \sum_{i=1}^{8} \left[ y^{(i)} \log(\widehat{y}^{(i)}) + (1 - y^{(i)}) \log(1 - \widehat{y}^{(i)}) \right] \\[3pt]
&= -\frac{1}{8} \left[ 0 \cdot \log(\widehat{y}^{(1)}) + 0 \cdot \log(\widehat{y}^{(2)}) + 0 \cdot \log(\widehat{y}^{(3)}) + 0 \cdot \log(\widehat{y}^{(4)}) + 1 \cdot \log(\widehat{y}^{(5)}) + 1 \cdot \log(\widehat{y}^{(6)}) + 1 \cdot \log(\widehat{y}^{(7)}) + 1 \cdot \log(\widehat{y}^{(8)}) \right] \\[3pt]
&\quad + (1 - 0) \cdot \log(1 - \widehat{y}^{(1)}) + (1 - 0) \cdot \log(1 - \widehat{y}^{(2)}) + (1 - 0) \cdot \log(1 - \widehat{y}^{(3)}) + (1 - 0) \cdot \log(1 - \widehat{y}^{(4)}) \\[3pt]
&\quad + (1 - 1) \cdot \log(1 - \widehat{y}^{(5)}) + (1 - 1) \cdot \log(1 - \widehat{y}^{(6)}) + (1 - 1) \cdot \log(1 - \widehat{y}^{(7)}) + (1 - 1) \cdot \log(1 - \widehat{y}^{(8)}) \\[3pt]
&= -\frac{1}{8} \left[ \log(\widehat{y}^{(5)}) + \log(\widehat{y}^{(6)}) + \log(\widehat{y}^{(7)}) + \log(\widehat{y}^{(8)}) + \log(1 - \widehat{y}^{(1)}) + \log(1 - \widehat{y}^{(2)}) + \log(1 - \widehat{y}^{(3)}) + \log(1 - \widehat{y}^{(4)}) \right] \\[3pt]
&= -\frac{1}{8} \left[ \sum_{i=5}^{8} \log(\widehat{y}^{(i)}) + \sum_{i=1}^{4} \log(1 - \widehat{y}^{(i)}) \right]
\end{aligned}
$$

### Python implementation for loss function and gradient computation using symbolic computation

```{python}
import sympy as sp
# Define symbols
w, b = sp.symbols('w b')
# Define the dataset (hours studied, pass/fail)
data = [(17, 0), (18, 0), (19, 0), (20, 0), (21, 1), (22, 1), (23, 1), (24, 1)]
def sigmoid(z):
    return 1 / (1 + sp.exp(-z))
def model(x):
    return sigmoid(w * x + b)
# Compute the loss function
loss_terms = []
for x_val, y_val in data:
    pred = model(x_val)
    loss_term = - (y_val * sp.log(pred) + (1 - y_val) * sp.log(1 - pred))
    loss_terms.append(loss_term)
n_samples = len(data)
loss_function = sum(loss_terms) / n_samples 
# Compute the gradients     
gradients = [sp.diff(loss_function, var) for var in [w, b]]
# Display results
def prettify(text: str, n_dashes=30, char="="):
    long_dash = n_dashes*char
    print("\n" + long_dash + "\n" + text + "\n" + long_dash)
prettify("Symbolic Loss Function")
sp.pprint(loss_function)
prettify("Gradient of the Loss Function")
for var, grad in zip(['dw', 'db'], gradients):
    print(f"{var} = {grad}")
```

## Problem description

The problem description for a classification problem is quite similar to the description of a regression problem in terms of the given dataset and the ultimate goal prediction, except that the label $y$ is not continous value. For a $K$-category classification problem, the label $y$ can take one of the $K$ finite values $\{0, \ldots, K-1\}$. Examples are:
 
- For binary classification problem of ECG data, we have $K = 1$ and the label can take value of either $0$ or $1$. 
- For hand-written digit classification, we have $10$-category classification with $K = 9$ and the label can take one value of the $10$ finite values $\{0, \ldots, 9\}$

For this reason, the dataset notation @eq-dataset-D and the matrix-presentation of this dataset @eq-dataset-matrix-presentation should be the same except that the label $y^{(i)}$ for all the samples can take only one value in the finite set $\{0, \ldots, K-1\}$ for the $K$-category classification problem.

We shall study 

## Logistic regression for binary classification